DROP TABLE ARTIST CASCADE;
DROP TABLE RECORD CASCADE;
DROP TABLE GENRE CASCADE;
DROP TABLE PRODUCT CASCADE;
DROP TABLE PRODUCTTYPE CASCADE;
DROP TABLE USERLIST CASCADE;
DROP TABLE COMMUNITY CASCADE;

CREATE TABLE ARTIST 
(
  A_ID NUMBER NOT NULL 
, A_NAME VARCHAR2(30) NOT NULL 
, DDAY DATE NOT NULL 
, MNUMBER NUMBER 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    A_ID 
  )
  ENABLE 
);

CREATE TABLE RECORD 
(
  R_ID NUMBER NOT NULL 
, R_NAME VARCHAR2(30) NOT NULL 
, RDAY DATE NOT NULL 
, SCOUNT NUMBER 
, A_ID NUMBER 
, G_ID NUMBER 
, CONSTRAINT RECORD_PK PRIMARY KEY 
  (
    R_ID 
  )
  ENABLE 
);

CREATE TABLE GENRE 
(
  G_ID NUMBER NOT NULL 
, G_NAME VARCHAR2(20) NOT NULL 
, CONSTRAINT GENRE_PK PRIMARY KEY 
  (
    G_ID 
  )
  ENABLE 
);

CREATE TABLE PRODUCT 
(
  P_ID NUMBER NOT NULL 
, P_NAME VARCHAR2(20) 
, PRICE NUMBER 
, A_ID NUMBER 
, PT_ID NUMBER 
, CONSTRAINT PRODUCT_PK PRIMARY KEY 
  (
    P_ID 
  )
  ENABLE 
);

CREATE TABLE PRODUCTTYPE 
(
  PT_ID NUMBER NOT NULL 
, PT_NAME VARCHAR2(20) NOT NULL 
, CONSTRAINT PRODUCTTYPE_PK PRIMARY KEY 
  (
    PT_ID 
  )
  ENABLE 
);

CREATE TABLE USERLIST 
(
  U_ID VARCHAR2(50) NOT NULL 
, U_NAME VARCHAR2(20) NOT NULL 
, PASSWORD VARCHAR2(30) NOT NULL 
, ADDRESS VARCHAR2(40) 
, EMAIL VARCHAR2(30) 
, PNUM VARCHAR2(13) 
, CARDID VARCHAR2(17) 
, MANAGER VARCHAR2(10) 
, CONSTRAINT USERLIST_PK PRIMARY KEY 
  (
    U_ID 
  )
  ENABLE 
);

CREATE TABLE COMMUNITY 
(
  C_ID NUMBER NOT NULL 
, TITLE VARCHAR2(50) NOT NULL 
, U_ID VARCHAR2(50) NOT NULL 
, C_DATE DATE NOT NULL 
, CONTENT VARCHAR2(100) 
, CAVAILABLE NUMBER 
, CONSTRAINT COMMUNITY_PK PRIMARY KEY 
  (
    C_ID 
  )
  ENABLE 
);




