INSERT INTO "STORE"."ARTIST" (A_ID, A_NAME, DDAY, MNUMBER) VALUES ('1', 'DAY6', TO_DATE('2015-09-07 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), '5');
INSERT INTO "STORE"."ARTIST" (A_ID, A_NAME, DDAY, MNUMBER) VALUES ('2', '¹Î¼ö', TO_DATE('2018-05-31 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1');
INSERT INTO "STORE"."ARTIST" (A_ID, A_NAME, DDAY, MNUMBER) VALUES ('3', 'DAYBREAK', TO_DATE('2007-09-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '4');
INSERT INTO "STORE"."ARTIST" (A_ID, A_NAME, DDAY, MNUMBER) VALUES ('4', 'PEPPERTONES', TO_DATE('2004-03-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS');

INSERT INTO "STORE"."GENRE" (G_ID, G_NAME) VALUES ('01', 'JAZZ');
INSERT INTO "STORE"."GENRE" (G_ID, G_NAME) VALUES ('02', 'POP');
INSERT INTO "STORE"."GENRE" (G_ID, G_NAME) VALUES ('03', 'ROCK');
INSERT INTO "STORE"."GENRE" (G_ID, G_NAME) VALUES ('04', 'KPOP');
